# Generated by Django 4.1.7 on 2023-03-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='rental',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
