# Generated by Django 4.1.7 on 2023-03-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_rental_options_rental_time_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-time_updated', '-date_posted']},
        ),
    ]
