# Generated by Django 4.1.7 on 2023-03-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_thread_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='unit_iamge',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
