# Generated by Django 4.1.7 on 2023-03-09 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_user_profile_realtor_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='REALTOR_PROFILE',
            new_name='RealtorProfile',
        ),
        migrations.RenameModel(
            old_name='USER_PROFILE',
            new_name='UserProfile',
        ),
    ]
